freebsd_instance:
  image: freebsd-12-1-release-amd64
  
env:
  CIRRUS_CLONE_DEPTH: 1

task:
  # This name gets reported as a build status in GitHub
  name: freebsd-12-1-release-amd64
  stateful: false
  setup_script:
    - pkg install -y curl wget gcc gmake zip pkgconf avahi libxml2 libjpeg-turbo gnutls sane-backends
  test_script:
    - mkdir ./prefix
    - gmake install DESTDIR=$(readlink -f ./prefix)
    - find ./prefix
    # case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; rm ghr.zip ; ./ghr -replace -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -c "${CIRRUS_CHANGE_IN_REPO}" continuous "${CIRRUS_WORKING_DIR}"/build/*zip ; esac
  only_if: $CIRRUS_TAG != 'continuous'
